import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const clashDisplay = localFont({
  src: [
    {
      path: "../public/font/ClashDisplay-Medium.ttf",
      weight: "500",
    },
  ],
  variable: "--font-clash-display",
});

const manrope = Manrope({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} ${clashDisplay.variable} relative min-h-screen antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
